import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fjalla = localFont({
  src: "../assets/fonts/Fjalla_One/FjallaOne-Regular.ttf"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fjalla.className}>{children}</body>
    </html>
  );
}
